language: python
sudo: false

env:
  global:
    # Doctr deploy key for ioos/atn-docs
    - secure: "MmrNP4Hjazn1HeZsAU6C7mpidVuc7x2HXii36FWvuixToPBe8ieOV2ebXzhPC87Ir5EWpURYToeqhWP74K09VPPL0LsxeU0rtwNvB7JWN4ZhY/c2nErtolj7JPQnHv+HuwdaBqc8p7wT00R4cWc12SDqUouUEHofe4YdunPrSGKSEOw0x5AXEotbYg9Y2nkOOW3Na9Wv8V3LmMqbcJ9ZxeAFowQl78JMhXPT/eoNBIbkyl4cqm7hoU32Hx4BcA8gLaDjQlhB5sEB2CR/4wOMFytTi7eL8se0GnOmo4DZ2KOc3gyH+Odlk52TOeYUPSKmRMSsUPC5T0zC5v/PEUiVQySNsjzBSsdqljiT65V7tRXG4EVMSCb89MCBsIGA6sn5PzVN60sooRCmNld7vwuph7KL6aahyNDpHQili+57TWkfyoHhOq4z7kzAJDPufOi4mj7b8ZL39kk5mZSlT0bP+CRUpauRe316BmXWs4jZjYQA2UHRo6s0TB3K/kISbh1J1NhILOqie/PMVLvduXz51Lny5t1Syr8ZNS203/OAJkkEqSJlFsOwIRhUSyPrhcBpHh4LvIJjCCUCyfVORhuqBIHP2NNDoX5a67TM+UMbYBwwJtzkO6Zf+O6+FIY4BjP2UoPV/lgTGTf0+AjTFhT5FBN/46z5wS9PGjnsm2M17G8="

python:
  - 3.6

script:
  - set -e
  - make html
  - doctr deploy . --built-docs _build/html
