language: python

sudo: false

env:
  global:
    # Doctr deploy key for ioos/atn-docs
    - secure: "AZqzVnSyY9wDsv/cziMeZ4TQta8idHe1xnEcLPb2OIix+HPogEd5AVflNEGh01FGLZhxGOyC1vs+sjlZEQ/bUmByYH/7aPSHRidCiCKeUedAGkmv0xS5cNEc8lO4Y/JeBrp20mOftFRXTEgVlqw7Oi4Q5dBp2L/Bbw3MQNqtPdSGC8HFdR/YGEb1TQAHpLb0z2B/y49UUgTEA6Qlub/eb9/MZMVXT7Py1GD9tDUWPZutW5amx/YvE2hLesDMnJ15ePKI19KPNla2lUfEFfV6ItrJif2eiN2qrL3j79o32hJ6Ho19TsPcLbF5+c5Id0Qu23jNvRw2oyoQanMl8CVDkNP26FbxdxdNCrZ3mF9A7d5eh+s3gqdcatbc0dBjJAqyggdqXmVeGLIlHJXwEWvXE494RVy8bYHoJYI6ttfVvNkCFiVofGY8JDvSOl1kzhf4EkjbhrJdghz5W0PgDwVDah3COutPOuyNCAxO9tPueWJ0ygjdJCYNkDBP85LtAB1g4yyQnf3EftAFkI0atVf2mo75mxsDpLY1ngkPnjRieKzY8IyiaR5Kt0aMhRvtVeWKR2nfqeZxwh8VgN6GIDp9KwnIqBpHkzJN7H/SaxM2pEowS8kft7ugpLvtehte3kqmNaFDSQjrBvH1YwVCrug3iP0n4R57r9Wc3izLUTHlZMI="

python:
  - 3.6

script:
  - set -e
  - make html
  - doctr deploy . --built-docs _build/html
