language: python

sudo: false

env:
  global:
    # Doctr deploy key for ioos/atn-docs
    - secure: "mwb218aeGQN1UxIdbXvIas5lcJeKDYbo6tHabG4J/OpJdxTltuBGt67hT1Lh/nJlDiD76m4FbDvGNkkfDEnI7CZEWbs+cREuJfvi+PMQuaPmKP03pEbMt8IfFbYJges4N7ATJXk4k04yLI6n+3RMetwJYlwNIZ541RRaSY9s1a+9nTAfBZ/fBy7KynnhGPEmc5OpyInbUCkA7gmKIMGJjWkD3JowxA/bBwRaaQtYCO8AXYTx8rpgXVXNDlJcapMvwcPXXwVjJl3jLcQvMyGaOndE0jh5rG8KV/ItGcI1AQa8u8Ci6qEvqgKbsmNJ9GH41YK3V42c+cpQ+0g5o3E7vAdtXe5ix8oO2i5wL2OEkYzAaQXN1NC7IrtPCW7Fz33Pc5/ZV5S4gh6JlpZB/dGspNrgPsvoyb8Qcat+YN7gv6hLjKrvVD7+ifdPUINgmbGEglEkLcUGo6AEYlEVZ/0pOXuId71uI05GQG+rUrtJNitoyKaRu2ExoIJG35eYETcHox5AV8GdaeAiGGMc6mA/yBbr2tps70iQznDY5azfqQkCIUl9fI0qGzR2mtfukwXkLohmIsvFd/Oocw2llvfF2sVQTSUVqdXNcJZH4A/jBy1hD2xGvIkB3XYzY7DEOt0GXcE2a41Ct0FOX25sJ/PADKW1Tgogo1eymrhAVbqUjOA="

python:
  - 3.6

script:
  - set -e
  - make html
  - doctr deploy . --built-docs _build/html
