sudo: false

language: python
python:
  - 3.6

env:
  global:
    - secure: "ipj4WQWRBy2IISA0+2dtkZZmdlGb0bs3BX3MZjwwcN8qEboeKWKfanT7uoY6sIod3bZdHjFeJy1o2VSrq6pJrhnmbk8t1s8lbrDAigifXxE6weeNiiSy9jX2qxiuvMY7TB35AblMhwJotRJdyCqDX3mZIXCNhI8+tGlGuCFmWk1SznpXIO1fbJeRLNn+ypUG3cCq05NvN5947lNwWr8JIjVs0WXDkp6qpEExM84pEnsks5MSnlh4yREpgiSxE6J8s1YQSVjXu410eUwW9T7ugMb9sK8ys0pX+dP7Ea2KYvsdmIqBzqnuS1tVXBY7Q3RVFsv/TsdxOk+pwH8qLfU94vqFaVGSbNGoAGOMHhBWfP8GC3midUc4S6+7M+mbH7ZUumH3T/Ccewwh65wslWCLQsP0egzzCTKK500Hfsrmq/bdhMbcfkx9olwCVyXxeN4TnNxDGymrHI3e60qhIVwG/N1SjL64hU5n4u+YW0HMrM2Zj9bHtCsobf4qk5qpvm4Lf9Fi4nBGVYJ1JoHYidWouES5PMGsmr3BEmREIE3fpkUVbx9voj4BDcl9XR059bjho2JPuOPgC04JO0R+JUDEtiWsVQKug6B2YA9q0GSIFe4a3sWl1Ry6qMy/SRDJOxE23f9hcQ47br+7VQtiI1kHY+g8GSuvIs0ltcwIb9esgf4="

script:
  - set -e
  - make html
  - doctr deploy . --built-docs _build/html
